import { textInputRule, markPasteRule, Mark } from "@tiptap/core";

interface EmojiReplacement {
  find: RegExp;
  replace: string;
}

const emojiReplacements: EmojiReplacement[] = [
  { find: /:\* $/, replace: "😘 " },
  { find: /=\* $/, replace: "😘 " },
  { find: /:\) $/, replace: "🙂 " },
  { find: /=\] $/, replace: "🙂 " },
  { find: /=\) $/, replace: "🙂 " },
  { find: /:\] $/, replace: "🙂 " },
  { find: /:X $/, replace: "😶 " },
  { find: /:# $/, replace: "😶 " },
  { find: /=X $/, replace: "😶 " },
  { find: /=x $/, replace: "😶 " },
  { find: /:x $/, replace: "😶 " },
  { find: /=# $/, replace: "😶 " },
  { find: /:O $/, replace: "😮 " },
  { find: /:o $/, replace: "😮 " },
  { find: /:P $/, replace: "😛 " },
  { find: /=P $/, replace: "😛 " },
  { find: /:p $/, replace: "😛  " },
  { find: /=p $/, replace: "😛 " },
  { find: /:Þ $/, replace: "😛 " },
  { find: /:þ $/, replace: "😛 " },
  { find: /:b $/, replace: "😛 " },
  { find: /d: $/, replace: "😛 " },
  { find: /-___- $/, replace: "😑 " },
  { find: /:'-\) $/, replace: "😂 " },
  { find: /':-\) $/, replace: "😅 " },
  { find: /':-D $/, replace: "😅 " },
  { find: />:-\) $/, replace: "😆 " },
  { find: /-__- $/, replace: "😑 " },
  { find: /':-\( $/, replace: "😓 " },
  { find: /:'-\( $/, replace: "😢 " },
  { find: />:-\( $/, replace: "😠 " },
  { find: /O:-\) $/, replace: "😇 " },
  { find: /0:-3 $/, replace: "😇 " },
  { find: /0:-\) $/, replace: "😇 " },
  { find: /0;\^\) $/, replace: "😇 " },
  { find: /O;-\) $/, replace: "😇 " },
  { find: /0;-\) $/, replace: "😇 " },
  { find: /O:-3 $/, replace: "😇 " },
  { find: /:'\) $/, replace: "😂 " },
  { find: /:-D $/, replace: "😃 " },
  { find: /':\) $/, replace: "😅 " },
  { find: /'=\) $/, replace: "😅 " },
  { find: /':D $/, replace: "😅 " },
  { find: /'=D $/, replace: "😅 " },
  { find: />:\) $/, replace: "😆 " },
  { find: />;\) $/, replace: "😆 " },
  { find: />=\) $/, replace: "😆 " },
  { find: /;-\) $/, replace: "😉 " },
  { find: /\*-\) $/, replace: "😉 " },
  { find: /;-\] $/, replace: "😉 " },
  { find: /;\^\) $/, replace: "😉 " },
  { find: /B-\) $/, replace: "😎 " },
  { find: /8-\) $/, replace: "😎 " },
  { find: /B-D $/, replace: "😎 " },
  { find: /8-D $/, replace: "😎 " },
  { find: /:-\* $/, replace: "😘 " },
  { find: /:\^\* $/, replace: "😘 " },
  { find: /:-\) $/, replace: "🙂 " },
  { find: /-_- $/, replace: "😑 " },
  { find: /:-X $/, replace: "😶 " },
  { find: /:-# $/, replace: "😶 " },
  { find: /:-x $/, replace: "😶 " },
  { find: />.< $/, replace: "😣 " },
  { find: /:-O $/, replace: "😮 " },
  { find: /:-o $/, replace: "😮 " },
  { find: /O_O $/, replace: "😮 " },
  { find: />:O $/, replace: "😮 " },
  { find: /:-P $/, replace: "😛 " },
  { find: /:-p $/, replace: "😛 " },
  { find: /:-Þ $/, replace: "😛 " },
  { find: /:-þ $/, replace: "😛 " },
  { find: /:-b $/, replace: "😛 " },
  { find: />:P $/, replace: "😜 " },
  { find: /X-P $/, replace: "😜 " },
  { find: /x-p $/, replace: "😜 " },
  { find: /':\( $/, replace: "😓 " },
  { find: /'=\( $/, replace: "😓 " },
  { find: />:\\ $/, replace: "😕 " },
  { find: />:\/ $/, replace: "😕 " },
  { find: /:-\/ $/, replace: "😕 " },
  { find: /:-. $/, replace: "😕 " },
  { find: />:\[ $/, replace: "😞 " },
  { find: /:-\( $/, replace: "😞 " },
  { find: /:-\[ $/, replace: "😞 " },
  { find: /:'\( $/, replace: "😢 " },
  { find: /;-\( $/, replace: "😢 " },
  { find: /#-\) $/, replace: "😵 " },
  { find: /%-\) $/, replace: "😵 " },
  { find: /X-\) $/, replace: "😵 " },
  { find: />:\( $/, replace: "😠 " },
  { find: /0:3 $/, replace: "😇 " },
  { find: /0:\) $/, replace: "😇 " },
  { find: /O:\) $/, replace: "😇 " },
  { find: /O=\) $/, replace: "😇 " },
  { find: /O:3 $/, replace: "😇 " },
  { find: /<\/3 $/, replace: "💔 " },
  { find: /:D $/, replace: "😃 " },
  { find: /=D $/, replace: "😃 " },
  { find: /;\) $/, replace: "😉 " },
  { find: /\*\) $/, replace: "😉 " },
  { find: /;\] $/, replace: "😉 " },
  { find: /;D $/, replace: "😉 " },
  { find: /B\) $/, replace: "😎 " },
  { find: /8\) $/, replace: "😎 " },
  { find: /:\/ $/, replace: "😕 " },
  { find: /:\\ $/, replace: "😕 " },
  { find: /=\/ $/, replace: "😕 " },
  { find: /=\\ $/, replace: "😕 " },
  { find: /:L $/, replace: "😕 " },
  { find: /=L $/, replace: "😕 " },
  { find: /:\( $/, replace: "😞 " },
  { find: /:\[ $/, replace: "😞 " },
  { find: /=\( $/, replace: "😞 " },
  { find: /;\( $/, replace: "😢 " },
  { find: /D: $/, replace: "😨 " },
  { find: /:\$ $/, replace: "😳 " },
  { find: /=\$ $/, replace: "😳 " },
  { find: /#-\) $/, replace: "😵 " },
  { find: /%-\) $/, replace: "😵 " },
  { find: /X-\) $/, replace: "😵 " },
  { find: /:@ $/, replace: "😠 " },
  { find: /<3 $/, replace: "❤️ " },

  { find: /:heart: $/, replace: "❤️ " },
  { find: /:heartpulse: $/, replace: "💗 " },
  { find: /:heartbeat: $/, replace: "💓 " },
  { find: /:heart_decoration: $/, replace: "💟 " },
  { find: /:two_hearts: $/, replace: "💕 " },
  { find: /:revolving_hearts: $/, replace: "💞 " },
  { find: /:cupid: $/, replace: "💘 " },
  { find: /:sparkling_heart: $/, replace: "💖 " },
  { find: /:sparkles: $/, replace: "✨ " },
  { find: /:star2: $/, replace: "🌟 " },
  { find: /:dizzy: $/, replace: "💫 " },
  { find: /:boom: $/, replace: "💥 " },
  { find: /:collision: $/, replace: "💥 " },
  { find: /:anger: $/, replace: "💢 " },
  { find: /:exclamation: $/, replace: "❗ " },
  { find: /:question: $/, replace: "❓ " },
  { find: /:grey_exclamation: $/, replace: "❕ " },
  { find: /:grey_question: $/, replace: "❔ " },
  { find: /:zzz: $/, replace: "💤 " },
  { find: /:dash: $/, replace: "💨 " },
  { find: /:sweat_drops: $/, replace: "💦 " },
  { find: /:notes: $/, replace: "🎶 " },
  { find: /:musical_note: $/, replace: "🎵 " },
  { find: /:fire: $/, replace: "🔥 " },
  { find: /:poop: $/, replace: "💩 " },
  { find: /:grinning: $/, replace: "😀 " },
  { find: /:smiley: $/, replace: "😃 " },
  { find: /:smile: $/, replace: "😄 " },
  { find: /:grin: $/, replace: "😁 " },
  { find: /:laughing: $/, replace: "😆 " },
  { find: /:satisfied: $/, replace: "😆 " },
  { find: /:sweat_smile: $/, replace: "😅 " },
  { find: /:rofl: $/, replace: "🤣 " },
  { find: /:joy: $/, replace: "😂 " },
  { find: /:slightly_smiling_face: $/, replace: "🙂 " },
  { find: /:upside_down_face: $/, replace: "🙃 " },
  { find: /:wink: $/, replace: "😉 " },
  { find: /:blush: $/, replace: "😊 " },
  { find: /:innocent: $/, replace: "😇 " },
  { find: /:smiling_face_with_three_hearts: $/, replace: "🥰 " },
  { find: /:heart_eyes: $/, replace: "😍 " },
  { find: /:star_struck: $/, replace: "🤩 " },
  { find: /:kissing_heart: $/, replace: "😘 " },
  { find: /:kissing: $/, replace: "😗 " },
  { find: /:relaxed: $/, replace: "☺️ " },
  { find: /:kissing_closed_eyes: $/, replace: "😚 " },
  { find: /:kissing_smiling_eyes: $/, replace: "😙 " },
  { find: /:yum: $/, replace: "😋 " },
  { find: /:stuck_out_tongue: $/, replace: "😛 " },
  { find: /:stuck_out_tongue_winking_eye: $/, replace: "😜 " },
  { find: /:zany_face: $/, replace: "🤪 " },
  { find: /:stuck_out_tongue_closed_eyes: $/, replace: "😝 " },
  { find: /:money_mouth_face: $/, replace: "🤑 " },
  { find: /:hugs: $/, replace: "🤗 " },
  { find: /:hand_over_mouth: $/, replace: "🤭 " },
  { find: /:shushing_face: $/, replace: "🤫 " },
  { find: /:thinking: $/, replace: "🤔 " },
  { find: /:zipper_mouth_face: $/, replace: "🤐 " },
  { find: /:raised_eyebrow: $/, replace: "🤨 " },
  { find: /:neutral_face: $/, replace: "😐 " },
  { find: /:expressionless: $/, replace: "😑 " },
  { find: /:no_mouth: $/, replace: "😶 " },
  { find: /:smirk: $/, replace: "😏 " },
  { find: /:unamused: $/, replace: "😒 " },
  { find: /:roll_eyes: $/, replace: "🙄 " },
  { find: /:grimacing: $/, replace: "😬 " },
  { find: /:lying_face: $/, replace: "🤥 " },
  { find: /:relieved: $/, replace: "😌 " },
  { find: /:pensive: $/, replace: "😔 " },
  { find: /:sleepy: $/, replace: "😪 " },
  { find: /:drooling_face: $/, replace: "🤤 " },
  { find: /:sleeping: $/, replace: "😴 " },
  { find: /:mask: $/, replace: "😷 " },
  { find: /:face_with_thermometer: $/, replace: "🤒 " },
  { find: /:face_with_head_bandage: $/, replace: "🤕 " },
  { find: /:nauseated_face: $/, replace: "🤢 " },
  { find: /:vomiting_face: $/, replace: "🤮 " },
  { find: /:sneezing_face: $/, replace: "🤧 " },
  { find: /:hot_face: $/, replace: "🥵 " },
  { find: /:cold_face: $/, replace: "🥶 " },
  { find: /:woozy_face: $/, replace: "🥴 " },
  { find: /:dizzy_face: $/, replace: "😵 " },
  { find: /:exploding_head: $/, replace: "🤯 " },
  { find: /:cowboy_hat_face: $/, replace: "🤠 " },
  { find: /:partying_face: $/, replace: "🥳 " },
  { find: /:sunglasses: $/, replace: "😎 " },
  { find: /:nerd_face: $/, replace: "🤓 " },
  { find: /:monocle_face: $/, replace: "🧐 " },
  { find: /:confused: $/, replace: "😕 " },
  { find: /:worried: $/, replace: "😟 " },
  { find: /:slightly_frowning_face: $/, replace: "🙁 " },
  { find: /:frowning_face: $/, replace: "☹️ " },
  { find: /:open_mouth: $/, replace: "😮 " },
  { find: /:hushed: $/, replace: "😯 " },
  { find: /:astonished: $/, replace: "😲 " },
  { find: /:flushed: $/, replace: "😳 " },
  { find: /:pleading_face: $/, replace: "🥺 " },
  { find: /:frowning: $/, replace: "😦 " },
  { find: /:anguished: $/, replace: "😧 " },
  { find: /:fearful: $/, replace: "😨 " },
  { find: /:cold_sweat: $/, replace: "😰 " },
  { find: /:disappointed_relieved: $/, replace: "😥 " },
  { find: /:cry: $/, replace: "😢 " },
  { find: /:sob: $/, replace: "😭 " },
  { find: /:scream: $/, replace: "😱 " },
  { find: /:confounded: $/, replace: "😖 " },
  { find: /:persevere: $/, replace: "😣 " },
  { find: /:disappointed: $/, replace: "😞 " },
  { find: /:sweat: $/, replace: "😓 " },
  { find: /:weary: $/, replace: "😩 " },
  { find: /:tired_face: $/, replace: "😫 " },
  { find: /:yawning_face: $/, replace: "🥱 " },
  { find: /:triumph: $/, replace: "😤 " },
  { find: /:rage: $/, replace: "😡 " },
  { find: /:angry: $/, replace: "😠 " },
  { find: /:cursing_face: $/, replace: "🤬 " },
  { find: /:smiling_imp: $/, replace: "😈 " },
  { find: /:imp: $/, replace: "👿 " },
  { find: /:skull: $/, replace: "💀 " },
  { find: /:skull_and_crossbones: $/, replace: "☠️ " },
  { find: /:hankey: $/, replace: "💩 " },
  { find: /:clown_face: $/, replace: "🤡 " },
  { find: /:japanese_ogre: $/, replace: "👹 " },
  { find: /:japanese_goblin: $/, replace: "👺 " },
  { find: /:ghost: $/, replace: "👻 " },
  { find: /:alien: $/, replace: "👽 " },
  { find: /:space_invader: $/, replace: "👾 " },
  { find: /:robot: $/, replace: "🤖 " },
  { find: /:smiley_cat: $/, replace: "😺 " },
  { find: /:smile_cat: $/, replace: "😸 " },
  { find: /:joy_cat: $/, replace: "😹 " },
  { find: /:heart_eyes_cat: $/, replace: "😻 " },
  { find: /:smirk_cat: $/, replace: "😼 " },
  { find: /:kissing_cat: $/, replace: "😽 " },
  { find: /:scream_cat: $/, replace: "🙀 " },
  { find: /:crying_cat_face: $/, replace: "😿 " },
  { find: /:pouting_cat: $/, replace: "😾 " },
  { find: /:palms_up_together: $/, replace: "🤲 " },
  { find: /:raised_hands: $/, replace: "🙌 " },
  { find: /:clap: $/, replace: "👏 " },
  { find: /:wave: $/, replace: "👋 " },
  { find: /:call_me_hand: $/, replace: "🤙 " },
  { find: /:thumbsup: $/, replace: "👍 " },
  { find: /:thumbsdown: $/, replace: "👎 " },
  { find: /:punch: $/, replace: "👊 " },
  { find: /:fist: $/, replace: "✊ " },
  { find: /:left_facing_fist: $/, replace: "🤛 " },
  { find: /:right_facing_fist: $/, replace: "🤜 " },
  { find: /:raised_back_of_hand: $/, replace: "🤚 " },
  { find: /:hand_splayed: $/, replace: "🖐 " },
  { find: /:vulcan_salute: $/, replace: "🖖 " },
  { find: /:ok_hand: $/, replace: "👌 " },
  { find: /:pinched_fingers: $/, replace: "🤌 " },
  { find: /:pinching_hand: $/, replace: "🤏 " },
  { find: /:v: $/, replace: "✌️ " },
  { find: /:crossed_fingers: $/, replace: "🤞 " },
  { find: /:love_you_gesture: $/, replace: "🤟 " },
  { find: /:metal: $/, replace: "🤘 " },
  { find: /:call_me: $/, replace: "🤙 " },
  { find: /:point_left: $/, replace: "👈 " },
  { find: /:point_right: $/, replace: "👉 " },
  { find: /:point_up_2: $/, replace: "👆 " },
  { find: /:middle_finger: $/, replace: "🖕 " },
  { find: /:point_down: $/, replace: "👇 " },
  { find: /:point_up: $/, replace: "☝️ " },
  { find: /:thumbsup: $/, replace: "👍 " },
  { find: /:thumbsdown: $/, replace: "👎 " },
  { find: /:fingers_crossed: $/, replace: "🤞 " },
  { find: /:vulcan_salute: $/, replace: "🖖 " },
  { find: /:clap: $/, replace: "👏 " },
  { find: /:raised_hands: $/, replace: "🙌 " },
  { find: /:open_hands: $/, replace: "👐 " },
  { find: /:palms_up_together: $/, replace: "🤲 " },
  { find: /:handshake: $/, replace: "🤝 " },
  { find: /:pray: $/, replace: "🙏 " },
  { find: /:writing_hand: $/, replace: "✍️ " },
  { find: /:nail_care: $/, replace: "💅 " },
  { find: /:selfie: $/, replace: "🤳 " },
  { find: /:muscle: $/, replace: "💪 " },
  { find: /:mechanical_arm: $/, replace: "🦾 " },
  { find: /:mechanical_leg: $/, replace: "🦿 " },
  { find: /:leg: $/, replace: "🦵 " },
  { find: /:foot: $/, replace: "🦶 " },
  { find: /:ear: $/, replace: "👂 " },
  { find: /:ear_with_hearing_aid: $/, replace: "🦻 " },
  { find: /:nose: $/, replace: "👃 " },
  { find: /:brain: $/, replace: "🧠 " },
  { find: /:tooth: $/, replace: "🦷 " },
  { find: /:skull: $/, replace: "💀 " },
];

export type EmojisOptions = {
  emojiReplacements?: EmojiReplacement[];

  /**
   * How to handle the emoji replacements.
   * @default "merge"
   */
  mode: "merge" | "override";
};

export const Emojis = Mark.create<EmojisOptions>({
  name: "EddiesEmojis",

  addOptions() {
    return {
      emojiReplacements: emojiReplacements,
      mode: "merge",
    };
  },

  addInputRules() {
    const replacements =
      this.options?.mode === "merge"
        ? [...emojiReplacements, ...this.options?.emojiReplacements!]
        : this.options?.emojiReplacements!;

    return replacements!.map((emojiReplacement) => {
      return textInputRule({
        find: emojiReplacement.find,
        replace: emojiReplacement.replace,
      });
    });
  },

  addPasteRules() {
    const replacements =
      this.options?.mode === "merge"
        ? [...emojiReplacements, ...this.options?.emojiReplacements!]
        : this.options?.emojiReplacements!;

    return replacements!.map((emojiReplacement) => {
      return markPasteRule({
        find: toPasteRule(emojiReplacement.find),
        type: this.type,
      });
    });
  },
});

const toPasteRule = (regex: RegExp) => {
  if (regex.toString().slice(-2) === "/$") {
    let rgx = regex.source.replace("$/", "/g");
    return new RegExp(rgx);
  }
  return regex;
};
